#!/usr/bin/expect -f

#########################################################
#														#
#						SmartWIFI						#
#					Project team BCDS					#
#														#
#########################################################
# date: 02/04/20
# autor: Team BCDS
# contact: raphael.barrasset@gmail.com; julien.castelain@outlook.fr; g.ducroux@outlook.fr; saint-amand.matthieu@orange.fr;

set vlan_connected [lindex $argv 0]
set vlan_unconnected [lindex $argv 1]

source ./ssh_connection
source ./admin_mode

send "sh vlan\r"

puts -nonewline "\033\[1;32m"; #GREEN
puts "\nDisplaying vlan configuration..."
puts "\033\[0m"; #Reset

expect "*#"

source ./unconnection

expect eof
