#!/usr/bin/expect -f

#########################################################
#														#
#						SmartWIFI						#
#					Project team BCDS					#
#														#
#########################################################
# date: 12/16/19
# autor: Team BCDS
# contact: raphael.barrasset@gmail.com; julien.castelain@outlook.fr; g.ducroux@outlook.fr; saint-amand.matthieu@orange.fr;

source ./ssh_connection
source ./admin_mode

send "show conf\r"

puts -nonewline "\033\[1;32m"; #GREEN
puts "\nDisplaying configuration..."
puts "\033\[0m"; #Reset

send "\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r"
expect "*#"

source ./unconnection

expect eof
